- name: Configure macOS
  hosts: all

  vars:
    homebrew_installed_packages:
      # Not sure why this isn't working
      # - 1password-cli
      - 1password
      - anki
      - ansible
      - arc
      - autopep8
      - awscli
      - bat
      - cairo
      - composer
      - difftastic
      - dropbox
      - dtrx
      - entr
      - eza
      - fd
      - ffmpeg
      - figma
      - fzf
      - gh
      - ghostty
      - git
      - git-lfs
      - gnu-sed
      - gum
      - htop
      - hugo
      - java
      - jq
      - keepingyouawake
      - linearmouse
      - mprocs
      - neovim
      - netnewswire
      - notion
      - notion-calendar
      - obsidian
      - orbstack
      - pango
      - php
      - pixman
      - pkg-config
      - raycast
      - ripgrep
      - shellcheck
      - shfmt
      - slack
      - spotify
      - starship
      - stow
      - stylua
      - tailscale
      - tldr
      - tmux
      - tree
      - unzip
      - vale
      - visual-studio-code
      - vlc
      # - volta
      - watch
      - wget
      - yamlfmt
      - yt-dlp
      - zoom
      - zsh

    # Commenting these out because I was hitting dockutil issues
    # dockitems_remove:
    #   - Launchpad
    #   - Safari
    #   - Mail
    #   - Maps
    #   - FaceTime
    #   - Calendar
    #   - Notes
    #   - Freeform
    #   - TV
    #   - Music
    #   - News
    #   - App Store
    #
    # dockitems_persist:
    #   - name: WezTerm
    #     path: /Applications/WezTerm.app
    #   - name: Arc
    #     path: /Applications/Arc.app
    #     pos: 2
    #   - name: Slack
    #     path: /Applications/Slack.app
    #     pos: 3
    #   - name: Spotify
    #     path: /Applications/Spotify.app
    #     pos: 4
    #   - name: Obsidian
    #     path: /Applications/Obsidian.app
    #   - name: Notion Calendar
    #     path: /Applications/Notion Calendar.app

    cargo_tmp: /tmp

  tasks:
    - import_tasks: tasks/dotfiles-mac.yaml
    - import_tasks: tasks/oh_my_zsh.yaml
    # - import_tasks: tasks/user-mac.yaml
    - name: Run mac config script
      command: ./macos.sh
      changed_when: false

  roles:
    - geerlingguy.mac.homebrew
    # - geerlingguy.mac.dock

- name: Install Cargo
  hosts: all

  tasks:
    - name: check if cargo is installed
      shell: command -v cargo
      register: cargo_exists
      changed_when: false
      failed_when: false

    - name: Download Installer
      when: cargo_exists.rc != 0
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: "0755"
        force: "yes"

    - name: install rust/cargo
      when: cargo_exists.rc != 0
      shell: /tmp/sh.rustup.rs -y

  # vars:
  #   cargo_tmp: /tmp
  #
  # roles:
  #   - robertdebock.cargo
