- name: Configure macOS
  hosts: all

  vars:
    homebrew_installed_packages:
      # Not sure why this isn't working
      # - 1password-cli
      - ansible
      - autopep8
      - bat
      - cairo
      - composer
      - dtrx
      - entr
      - eza
      - fd
      - fzf
      - gh
      - git
      - git-lfs
      - gnu-sed
      - htop
      - java
      - jq
      - mprocs
      - neovim
      - pango
      - php
      - pixman
      - pkg-config
      - ripgrep
      - shellcheck
      - shfmt
      - starship
      - stow
      - stylua
      - tldr
      - tmux
      - tree
      - unzip
      - vale
      - volta
      - watch
      - wget
      - yamlfmt
      - zsh

    homebrew_cask_apps:
      - 1password
      - alacritty
      - arc
      - dropbox
      - figma
      - keepingyouawake
      - linear-linear
      - netnewswire
      - notion-calendar
      - obsidian
      - orbstack
      - raycast
      - slack
      - tailscale
      - spotify
      - visual-studio-code
      - wezterm
      - zoom

    dockitems_remove:
      - Launchpad
      - Safari
      - Mail
      - Maps
      - FaceTime
      - Calendar
      - Notes
      - Freeform
      - TV
      - Music
      - News
      - App Store

    dockitems_persist:
      - name: WezTerm
        path: /Applications/WezTerm.app
      - name: Arc
        path: /Applications/Arc.app
        pos: 2
      - name: Slack
        path: /Applications/Slack.app
        pos: 3
      - name: Spotify
        path: /Applications/Spotify.app
        pos: 4
      - name: Obsidian
        path: /Applications/Obsidian.app
      - name: Notion Calendar
        path: /Applications/Notion Calendar.app

    cargo_tmp: /tmp

  tasks:
    - import_tasks: tasks/dotfiles-mac.yaml
    - import_tasks: tasks/oh_my_zsh.yaml
    # - import_tasks: tasks/user-mac.yaml
    - name: Run mac config script
      command: ./macos.sh
      changed_when: false

  roles:
    - geerlingguy.mac.homebrew
    - geerlingguy.mac.dock

- name: Install Cargo
  hosts: all

  tasks:
    - name: check if cargo is installed
      shell: command -v cargo
      register: cargo_exists
      changed_when: false
      failed_when: false

    - name: Download Installer
      when: cargo_exists.rc != 0
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: "0755"
        force: "yes"

    - name: install rust/cargo
      when: cargo_exists.rc != 0
      shell: /tmp/sh.rustup.rs -y

  # vars:
  #   cargo_tmp: /tmp
  #
  # roles:
  #   - robertdebock.cargo
