---
- name: Configure system
  hosts: localhost
  become: true

  roles:
    - role: ansible.builtin.include_role
      tasks_from: user.yaml
    - role: ansible.builtin.include_role
      tasks_from: packages.yaml
    - role: ansible.builtin.include_role
      tasks_from: locale.yaml
