- name: Set stow directory
  set_fact:
    dotfiles_directory: "{{ ansible_env.HOME }}/.dotfiles"

- name: Clone dotfiles repo
  git:
    repo: "https://github.com/jamesbvaughan/dotfiles.git"
    dest: "{{ dotfiles_directory }}"
    update: false

- name: Stow common config files
  shell: "stow --target {{ ansible_env.HOME }} --verbose=2 ghostty git lf luacheck mprocs neovim tmux vale zsh"
  args:
    chdir: "{{ dotfiles_directory }}/common"
  register: result
  changed_when: 'result.stderr is search("LINK: ")'

- name: Stow Linux config files
  shell: "stow --target {{ ansible_env.HOME }} --verbose=2 hushlogin mpv qutebrowser sway wob zathura"
  args:
    chdir: "{{ dotfiles_directory }}/linux"
  register: result
  changed_when: 'result.stderr is search("LINK: ")'
