- name: Install shell utilities
  pacman:
    name:
      - bat         # cat replacement
      - eza         # ls replacement
      - fd          # find replacement
      - fzf         # a fuzzy-finder
      - ripgrep     # grep replacement
      - starship    # terminal prompt
      - zsh

- name: Install Oh My Zsh
  git:
    repo: 'https://github.com/ohmyzsh/ohmyzsh.git'
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh"
    update: false
