---
- name: Install dotfiles
  hosts: localhost
  connection: local

  vars:
    stow_packages:
      common:
        - git
        - lf
        - luacheck
        - neovim
        - tmux
        - vale
        - wezterm
        - zsh
      linux:
        - hushlogin
        - qutebrowser
        - sway
        - wob
        - zathura
      macos:
        - yabai

  tasks:
    - name: Set stow directory
      set_fact:
        dotfiles_directory: "{{ ansible_env.HOME }}/.dotfiles"

    - name: Clone dotfiles repo
      git:
        repo: 'https://github.com/jamesbvaughan/dotfiles.git'
        dest: "{{ dotfiles_directory }}"
        update: false

    - name: Stow common packages
      shell: "stow --target {{ ansible_env.HOME }} {{stow_packages.common | join(' ')}} --verbose=2"
      args:
        chdir: "{{ dotfiles_directory }}/common"
      register: result
      changed_when: 'result.stderr is search("LINK: ")'

    - name: Stow linux packages
      shell: "stow --target {{ ansible_env.HOME }} {{stow_packages.linux | join(' ')}} --verbose=2"
      args:
        chdir: "{{ dotfiles_directory }}/linux"
      register: result
      changed_when: 'result.stderr is search("LINK: ")'
      when: ansible_distribution == "Archlinux"

    - name: Stow macOS packages
      shell: "stow --target {{ ansible_env.HOME }} {{stow_packages.macos | join(' ')}} --verbose=2"
      args:
        chdir: "{{ dotfiles_directory }}/macos"
      register: result
      changed_when: 'result.stderr is search("LINK: ")'
      when: ansible_distribution == "MacOSX"

    # TODO: Figure out what the distribution name is on mac
    # - name: log
    #   debug:
    #     msg: "{{ ansible_distribution }}"
