---
- name: Install packages for linux machines
  hosts: localhost

  tasks:
    # - name: Update the cache and upgrade packages
    #   kewlfft.aur.aur:
    #     update_cache: true
    #     upgrade: true

    - name: Install base utilities
      kewlfft.aur.aur:
        name:
          - base
          - base-devel
          - intel-ucode
          - linux
          - linux-firmware

    - name: Install sway environment packages
      kewlfft.aur.aur:
        name:
          - bemenu            # a dmenu-like input picker
          - j4-dmenu-desktop  # an application picker
          - grimshot          # screenshot utility
          - rofi              # another dmenu-like input picker
          - spotify-tui       # spotify client that my waybar config uses
          - sway              # the window manager
          - swaybg            # sets the wallpaper
          - swayidle
          - swaylock-effects  # lock screen
          - swaync            # notification daemon and sidebar
          - waybar            # toolbars
          - wl-clipboard      # wayland clipboard tool
          - wob               # progress indicator (for volume and brighness)

    - name: Install other linux-specific packages
      kewlfft.aur.aur:
        name:
          - brightnessctl
          - chrony
          - dmidecode
          - efibootmgr
          - gammastep     # like f.lux
          - gnome-keyring
          - htop
          - networkmanager
          - networkmanager-dispatcher-chrony
          - python-adblock # needed for qutebrowser's ad blocking
          - python-requests # needed for various things, including waybar weather
          - qutebrowser
          - trash-cli # needed for obsidian's trash feature
          - yay

    - name: Install general programs
      kewlfft.aur.aur:
        name:
          - 1password
          - 1password-cli
          - ansible
          - ansible-core
          - bat
          - dtrx
          - docker
          - eza         # ls replacement
          - fzf
          - git
          - jq
          - mprocs
          - neovim
          - obsidian
          - ripgrep
          - shellcheck
          - shfmt
          - spotify-launcher
          - starship
          - stow
          - tldr
          - tree
          - unzip
          - vale
          - volta-bin
          - wezterm
          - zsh


# laptop power management
- name: Install and set up tlp
  hosts: localhost

  tasks:
    - name: Install tlp programs
      kewlfft.aur.aur:
        name:
          - ethtool       # disables wake-on-lan
          - tlp           # laptop power management
          - smartmontools # more info in tlp-stat

    - name: Enable the tlp service
      become: true
      systemd_service:
        name: tlp
        state: started
        enabled: true

    - name: Mask the rfkill service
      become: true
      systemd_service:
        name: systemd-rfkill.service
        state: stopped
        enabled: false
        masked: true

    - name: Mask the rfkill socket
      become: true
      systemd_service:
        name: systemd-rfkill.socket
        state: stopped
        enabled: false
        masked: true


# cpu temp management (intel only)
- name: Install and set up thermald
  become: true
  hosts: localhost

  tasks:
    - name: Install thermald programs
      pacman:
        name:
          - thermald

    - name: Enable the service
      systemd_service:
        name: thermald
        state: started
        enabled: true


- name: Install and set up docker
  hosts: localhost

  tasks:
    - name: Install docker
      become: true
      pacman:
        name:
          - docker
          - docker-compose

    - name: Enable docker service socket
      become: true
      systemd_service:
        name: docker.socket
        state: started
        enabled: true
