---
- name: Install packages for macs
  hosts: localhost

  tasks:
    - name: Update homebrew
      homebrew:
        update_homebrew: true

    - name: Upgrade packages
      homebrew:
        upgrade_all: true

    - name: Install packages
      homebrew:
        name:
          - 1password
          - 1password-cli
          - ansible
          - ansible-core
          - autopep8
          - bat
          - dtrx
          - eza
          - fzf
          - git
          - htop
          - neovim
          - obsidian
          - ripgrep
          - shellcheck
          - shfmt
          - starship
          - stow
          - tldr
          - tree
          - unzip
          - vale
          - volta-bin
          - wezterm
          - zsh
